# Generated by Django 5.2.7 on 2026-01-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
